databases:
  - name: postgres
    ipAllowList: []
    databaseName: search
    user: search
    plan: free

services:
  - type: web
    name: search
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false