databases:
  - name: search
    databaseName: search
    user: search

services:
  - type: web
    name: search
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: search
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false