
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_box_development

test:
  <<: *default
  database: search_box_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: search_box_production
  username: search_box
  password: <%= ENV["SEARCH_BOX_DATABASE_PASSWORD"] %>
